{% set name = "brainglobe-utils" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainglobe-utils-{{ version }}.tar.gz
  sha256: 49c2f1905200eaae8547e2cbda519d09200ed27c33a05d60e572476c164ba8eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8.0
    - natsort
    - pandas
    - psutil
    - slurmio
    - configobj
    - tqdm
    - pyyaml
    - scipy
    - scikit-image

test:
  imports:
    - brainglobe_utils
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  summary: Shared general purpose tools for the BrainGlobe project
  home: https://github.com/brainglobe/BrainGlobe-utils
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - willGraham01
    - adamltyson
